# Generated by Django 4.2.16 on 2024-11-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0002_voter_precinct_voter_street_number_voter_v20state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter", name="voter_id", field=models.CharField(max_length=12),
        ),
    ]
