# Generated by Django 4.2.16 on 2024-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_voter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter", name="dob", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="dor", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="party", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="voter_id", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="zipcode", field=models.TextField(),
        ),
    ]
