# Generated by Django 4.2.16 on 2024-11-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0004_alter_voter_dob_alter_voter_dor_alter_voter_party_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="voter_id",),
    ]
