# Generated by Django 4.2.16 on 2024-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0006_alter_voter_apartment_number_alter_voter_dob_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter", name="v20state", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="v21primary", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="v21town", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="v22general", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter", name="v23town", field=models.TextField(),
        ),
    ]
