# Generated by Django 4.2.16 on 2024-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image_file",),
        migrations.AddField(
            model_name="product", name="image_url", field=models.URLField(blank=True),
        ),
    ]
