# Generated by Django 4.2.16 on 2024-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_product_image_file_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Sell",),
    ]
