# Generated by Django 4.2.16 on 2024-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_order_orderitem_delete_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in cart", "In Cart"),
                    ("shipping", "Shipping"),
                    ("complete", "Complete"),
                ],
                max_length=10,
            ),
        ),
    ]
