# Generated by Django 4.2.16 on 2024-11-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_user",
                to="project.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cart", "Cart"),
                    ("shipping", "Shipping"),
                    ("complete", "Complete"),
                ],
                max_length=10,
            ),
        ),
    ]
