# Generated by Django 4.2.16 on 2024-11-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_orderitem_user_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="image_url", field=models.URLField(blank=True),
        ),
    ]
