# Generated by Django 4.2.16 on 2024-11-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project",
            "0009_remove_review_name_review_user_alter_product_seller_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="user",),
        migrations.RemoveField(model_name="orderitem", name="user",),
        migrations.RemoveField(model_name="review", name="user",),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="project.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_profile",
                to="project.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="project.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="project.profile",
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
