# Generated by Django 4.2.16 on 2024-11-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_remove_profile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="profile",),
    ]
