# Generated by Django 4.2.16 on 2024-11-29 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_profile_user_review_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(model_name="order", name="profile",),
        migrations.RemoveField(model_name="orderitem", name="profile",),
        migrations.RemoveField(model_name="review", name="profile",),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="project.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_user",
                to="project.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="project.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="project.user",
            ),
        ),
        migrations.DeleteModel(name="Profile",),
    ]
