# Generated by Django 4.2.16 on 2024-11-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_user_remove_order_profile_remove_orderitem_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.user"
            ),
        ),
    ]
