# Generated by Django 4.2.16 on 2024-11-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_alter_review_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Profile",),
        migrations.RenameField(
            model_name="review", old_name="user", new_name="profile",
        ),
        migrations.RemoveField(model_name="order", name="user",),
        migrations.RemoveField(model_name="orderitem", name="user",),
        migrations.AddField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="project.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_profile",
                to="project.profile",
            ),
            preserve_default=False,
        ),
    ]
