# Generated by Django 4.2.16 on 2024-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_remove_orderitem_profile_orderitem_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
