# Generated by Django 4.2.16 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_image_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.TextField(),
        ),
    ]
