# Generated by Django 4.2.16 on 2024-12-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_image_timestamp"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="timestamp",),
        migrations.RemoveField(model_name="order", name="timestamp",),
        migrations.RemoveField(model_name="review", name="timestamp",),
    ]
