# Generated by Django 4.2.16 on 2024-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_remove_image_timestamp_remove_order_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
