# Generated by Django 4.2.16 on 2024-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_alter_orderitem_order_completedorderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.DeleteModel(name="CompletedOrderHistory",),
    ]
