# Generated by Django 4.2.16 on 2024-12-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_alter_product_price_delete_completedorderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.TextField(),
        ),
    ]
