# Generated by Django 4.2.16 on 2024-10-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image", old_name="image", new_name="image_file",
        ),
        migrations.RenameField(
            model_name="image", old_name="message", new_name="status_message",
        ),
    ]
